//! Canonical volume-mount model types.

#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// Kind of volume mount.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "lowercase"))]
pub enum VolumeKind {
    /// Named Docker volume.
    Volume,
    /// Bind mount from a host path.
    Bind,
    /// Anonymous volume (source is generated by the runtime).
    Anonymous,
}

/// Canonical volume mount in the project model.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct CanonicalVolume {
    /// Mount kind: named volume, bind, or anonymous.
    pub kind: VolumeKind,
    /// Source: named volume name or host path. `None` for anonymous mounts.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub source: Option<String>,
    /// Target (container) path.
    pub target: String,
    /// Whether the mount is read-only.
    pub read_only: bool,
}
