#!/usr/bin/env bash
set -eu

out_dir="${SUSUN_RELEASE_DOCS_OUT_DIR:-target/release-docs}"
doc_path="docs/generated/capability-and-compatibility.md"

mkdir -p "$out_dir" "$(dirname "$doc_path")"

cargo run -p susun-cli -- compatibility > "$out_dir/capability-matrix.json"
cargo run -p susun-cli -- compatibility --corpus fixtures/compatibility/corpus.json > "$out_dir/oracle-plan.json"
cargo run -p susun-cli -- compatibility --security-audit fixtures/compatibility/corpus.json > "$out_dir/security-audit.json"
cp fixtures/compatibility/version-matrix.json "$out_dir/version-matrix.json"
cp fixtures/compatibility/performance-budgets.json "$out_dir/performance-budgets.json"
cp fixtures/compatibility/real-world-catalog.json "$out_dir/real-world-catalog.json"
cp fixtures/compatibility/release-readiness.json "$out_dir/release-readiness.json"

python - "$out_dir" "$doc_path" <<'PY'
import json
import sys
from pathlib import Path

out_dir = Path(sys.argv[1])
doc_path = Path(sys.argv[2])

matrix = json.loads((out_dir / "capability-matrix.json").read_text())
oracle = json.loads((out_dir / "oracle-plan.json").read_text())
audit = json.loads((out_dir / "security-audit.json").read_text())
versions = json.loads((out_dir / "version-matrix.json").read_text())
budgets = json.loads((out_dir / "performance-budgets.json").read_text())
real_world = json.loads((out_dir / "real-world-catalog.json").read_text())
readiness = json.loads((out_dir / "release-readiness.json").read_text())

lines = [
    "# Susun Capability and Compatibility Report",
    "",
    "> Generated by `scripts/generate-release-docs` from Susun compatibility artifacts.",
    "",
    "## Capability Matrix",
    "",
    f"- Schema: {matrix['schema_version']['major']}.{matrix['schema_version']['minor']}",
    f"- Susun version: {matrix['susun_version']}",
    f"- Compose reference: {matrix['compose_reference']}",
    "",
    "| Feature | Support | Scope |",
    "| --- | --- | --- |",
]

for name, feature in sorted(matrix["features"].items()):
    lines.append(f"| {name} | {feature['support']} | {feature['scope']} |")

lines.extend([
    "",
    "## Compatibility Corpus",
    "",
    f"- Fixtures: {len(oracle)}",
    "",
    "| Fixture | Operations |",
    "| --- | --- |",
])

for fixture in sorted(oracle, key=lambda item: item["fixture_id"]):
    ops = ", ".join(sorted({invocation["operation"] for invocation in fixture["invocations"]}))
    lines.append(f"| {fixture['fixture_id']} | {ops} |")

lines.extend([
    "",
    "## Security Audit",
    "",
    f"- Corpus: {audit['corpus']}",
    f"- Fixture count: {audit['fixture_count']}",
    f"- Findings: {len(audit['findings'])}",
    "",
    "| Severity | Code | Fixture | Message |",
    "| --- | --- | --- | --- |",
])

for finding in audit["findings"]:
    fixture = finding.get("fixture_id") or ""
    lines.append(
        f"| {finding['severity']} | {finding['code']} | {fixture} | {finding['message']} |"
    )

lines.extend([
    "",
    "## Version Matrix",
    "",
    f"- Schema: {versions['schema_version']['major']}.{versions['schema_version']['minor']}",
    f"- Policy: {versions['policy']}",
    "",
    "| ID | Runner | Docker Engine | Docker Compose | BuildKit | Default CI |",
    "| --- | --- | --- | --- | --- | --- |",
])

for entry in versions["entries"]:
    lines.append(
        f"| {entry['id']} | {entry['runner']} | {entry['docker_engine']} | "
        f"{entry['docker_compose']} | {entry['buildkit']} | {entry['default_in_ci']} |"
    )

if versions.get("deferred"):
    lines.extend(["", "Deferred coverage:"])
    lines.extend(f"- {item}" for item in versions["deferred"])

lines.extend([
    "",
    "## Performance Budgets",
    "",
    f"- Schema: {budgets['schema_version']['major']}.{budgets['schema_version']['minor']}",
    f"- Scope: {budgets['scope']}",
    "",
    "| Benchmark | Unit | Max | Description |",
    "| --- | --- | --- | --- |",
])

for budget in budgets["budgets"]:
    lines.append(
        f"| {budget['name']} | {budget['unit']} | {budget['max']} | {budget['description']} |"
    )

if budgets.get("notes"):
    lines.extend(["", "Notes:"])
    lines.extend(f"- {note}" for note in budgets["notes"])

lines.extend([
    "",
    "## Real-World Compatibility",
    "",
    f"- Catalog: {real_world['name']}",
    f"- Patterns: {len(real_world['patterns'])}",
    "",
    "| Pattern | Support | Fixtures | Operations | Evidence |",
    "| --- | --- | --- | --- | --- |",
])

for pattern in sorted(real_world["patterns"], key=lambda item: item["id"]):
    fixtures = ", ".join(pattern["fixtures"])
    operations = ", ".join(pattern["operations"])
    lines.append(
        f"| {pattern['title']} | {pattern['support']} | {fixtures} | {operations} | {pattern['evidence']} |"
    )

deferred = [
    (pattern["title"], item)
    for pattern in real_world["patterns"]
    for item in pattern.get("deferred", [])
]
if deferred:
    lines.extend(["", "Real-world compatibility gaps:"])
    for title, item in deferred:
        lines.append(f"- {title}: {item}")

lines.extend([
    "",
    "## Release Readiness",
    "",
    f"- Version: {readiness['release_version']}",
    f"- Phase: {readiness['phase']}",
    f"- Status: {readiness['status']}",
    f"- Summary: {readiness['summary']}",
    "",
    "| Gate | Command | Purpose |",
    "| --- | --- | --- |",
])

for gate in readiness["required_gates"]:
    lines.append(f"| {gate['id']} | `{gate['command']}` | {gate['purpose']} |")

if readiness.get("deferred"):
    lines.extend(["", "Release readiness deferred work:"])
    lines.extend(f"- {item}" for item in readiness["deferred"])

lines.append("")
doc_path.write_text("\n".join(lines))
print(f"wrote {doc_path}")
PY
