$ErrorActionPreference = "Stop"

$outDir = "target/release-docs"
$docPath = "docs/generated/capability-and-compatibility.md"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $docPath) | Out-Null

cargo run -p susun-cli -- compatibility | Set-Content -LiteralPath "$outDir/capability-matrix.json"
cargo run -p susun-cli -- compatibility --corpus fixtures/compatibility/corpus.json | Set-Content -LiteralPath "$outDir/oracle-plan.json"
cargo run -p susun-cli -- compatibility --security-audit fixtures/compatibility/corpus.json | Set-Content -LiteralPath "$outDir/security-audit.json"
Copy-Item -LiteralPath "fixtures/compatibility/version-matrix.json" -Destination "$outDir/version-matrix.json" -Force
Copy-Item -LiteralPath "fixtures/compatibility/performance-budgets.json" -Destination "$outDir/performance-budgets.json" -Force
Copy-Item -LiteralPath "fixtures/compatibility/real-world-catalog.json" -Destination "$outDir/real-world-catalog.json" -Force
Copy-Item -LiteralPath "fixtures/compatibility/release-readiness.json" -Destination "$outDir/release-readiness.json" -Force

$matrix = Get-Content -LiteralPath "$outDir/capability-matrix.json" -Raw | ConvertFrom-Json
$oracle = Get-Content -LiteralPath "$outDir/oracle-plan.json" -Raw | ConvertFrom-Json
$audit = Get-Content -LiteralPath "$outDir/security-audit.json" -Raw | ConvertFrom-Json
$versions = Get-Content -LiteralPath "$outDir/version-matrix.json" -Raw | ConvertFrom-Json
$budgets = Get-Content -LiteralPath "$outDir/performance-budgets.json" -Raw | ConvertFrom-Json
$realWorld = Get-Content -LiteralPath "$outDir/real-world-catalog.json" -Raw | ConvertFrom-Json
$readiness = Get-Content -LiteralPath "$outDir/release-readiness.json" -Raw | ConvertFrom-Json

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Susun Capability and Compatibility Report")
$lines.Add("")
$lines.Add('> Generated by `scripts/generate-release-docs` from Susun compatibility artifacts.')
$lines.Add("")
$lines.Add("## Capability Matrix")
$lines.Add("")
$lines.Add("- Schema: $($matrix.schema_version.major).$($matrix.schema_version.minor)")
$lines.Add("- Susun version: $($matrix.susun_version)")
$lines.Add("- Compose reference: $($matrix.compose_reference)")
$lines.Add("")
$lines.Add("| Feature | Support | Scope |")
$lines.Add("| --- | --- | --- |")
foreach ($feature in $matrix.features.PSObject.Properties | Sort-Object Name) {
    $lines.Add(("| {0} | {1} | {2} |" -f $feature.Name, $feature.Value.support, $feature.Value.scope))
}
$lines.Add("")
$lines.Add("## Compatibility Corpus")
$lines.Add("")
$lines.Add("- Fixtures: $($oracle.Count)")
$lines.Add("")
$lines.Add("| Fixture | Operations |")
$lines.Add("| --- | --- |")
foreach ($fixture in $oracle | Sort-Object fixture_id) {
    $ops = ($fixture.invocations | ForEach-Object { $_.operation } | Sort-Object -Unique) -join ", "
    $lines.Add(("| {0} | {1} |" -f $fixture.fixture_id, $ops))
}
$lines.Add("")
$lines.Add("## Security Audit")
$lines.Add("")
$lines.Add("- Corpus: $($audit.corpus)")
$lines.Add("- Fixture count: $($audit.fixture_count)")
$lines.Add("- Findings: $($audit.findings.Count)")
$lines.Add("")
$lines.Add("| Severity | Code | Fixture | Message |")
$lines.Add("| --- | --- | --- | --- |")
foreach ($finding in $audit.findings) {
    $fixture = if ($finding.fixture_id) { $finding.fixture_id } else { "" }
    $lines.Add(("| {0} | {1} | {2} | {3} |" -f $finding.severity, $finding.code, $fixture, $finding.message))
}
$lines.Add("")
$lines.Add("## Version Matrix")
$lines.Add("")
$lines.Add("- Schema: $($versions.schema_version.major).$($versions.schema_version.minor)")
$lines.Add("- Policy: $($versions.policy)")
$lines.Add("")
$lines.Add("| ID | Runner | Docker Engine | Docker Compose | BuildKit | Default CI |")
$lines.Add("| --- | --- | --- | --- | --- | --- |")
foreach ($entry in $versions.entries) {
    $lines.Add(("| {0} | {1} | {2} | {3} | {4} | {5} |" -f $entry.id, $entry.runner, $entry.docker_engine, $entry.docker_compose, $entry.buildkit, $entry.default_in_ci))
}
if ($versions.deferred.Count -gt 0) {
    $lines.Add("")
    $lines.Add("Deferred coverage:")
    foreach ($item in $versions.deferred) {
        $lines.Add("- $item")
    }
}
$lines.Add("")
$lines.Add("## Performance Budgets")
$lines.Add("")
$lines.Add("- Schema: $($budgets.schema_version.major).$($budgets.schema_version.minor)")
$lines.Add("- Scope: $($budgets.scope)")
$lines.Add("")
$lines.Add("| Benchmark | Unit | Max | Description |")
$lines.Add("| --- | --- | --- | --- |")
foreach ($budget in $budgets.budgets) {
    $lines.Add(("| {0} | {1} | {2} | {3} |" -f $budget.name, $budget.unit, $budget.max, $budget.description))
}
if ($budgets.notes.Count -gt 0) {
    $lines.Add("")
    $lines.Add("Notes:")
    foreach ($note in $budgets.notes) {
        $lines.Add("- $note")
    }
}

$lines.Add("")
$lines.Add("## Real-World Compatibility")
$lines.Add("")
$lines.Add("- Catalog: $($realWorld.name)")
$lines.Add("- Patterns: $(@($realWorld.patterns).Count)")
$lines.Add("")
$lines.Add("| Pattern | Support | Fixtures | Operations | Evidence |")
$lines.Add("| --- | --- | --- | --- | --- |")
foreach ($pattern in @($realWorld.patterns) | Sort-Object id) {
    $fixtures = (@($pattern.fixtures) -join ", ")
    $operations = (@($pattern.operations) -join ", ")
    $lines.Add(("| {0} | {1} | {2} | {3} | {4} |" -f $pattern.title, $pattern.support, $fixtures, $operations, $pattern.evidence))
}

$deferred = New-Object System.Collections.Generic.List[object]
foreach ($pattern in @($realWorld.patterns)) {
    foreach ($item in @($pattern.deferred)) {
        $deferred.Add([PSCustomObject]@{ Title = $pattern.title; Item = $item })
    }
}
if ($deferred.Count -gt 0) {
    $lines.Add("")
    $lines.Add("Real-world compatibility gaps:")
    foreach ($entry in $deferred) {
        $lines.Add("- $($entry.Title): $($entry.Item)")
    }
}

$lines.Add("")
$lines.Add("## Release Readiness")
$lines.Add("")
$lines.Add("- Version: $($readiness.release_version)")
$lines.Add("- Phase: $($readiness.phase)")
$lines.Add("- Status: $($readiness.status)")
$lines.Add("- Summary: $($readiness.summary)")
$lines.Add("")
$lines.Add("| Gate | Command | Purpose |")
$lines.Add("| --- | --- | --- |")
foreach ($gate in @($readiness.required_gates)) {
    $lines.Add(("| {0} | {1} | {2} |" -f $gate.id, $gate.command, $gate.purpose))
}

if (@($readiness.deferred).Count -gt 0) {
    $lines.Add("")
    $lines.Add("Release readiness deferred work:")
    foreach ($item in @($readiness.deferred)) {
        $lines.Add("- $item")
    }
}

Set-Content -LiteralPath $docPath -Value $lines
Write-Host "wrote $docPath"
